# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               David Crayfords Blog
tagline:             'Tech, food and footie'
description:         'A blog about tech, food, football and other drivel'
url:                 http://lanyon.getpoole.com
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Pagination
gems: [jekyll-paginate]
